steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/omega-terrain-450302-m3/html-site
      - -f
      - Dockerfile    
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/omega-terrain-450302-m3/html-site

images:
  - gcr.io/omega-terrain-450302-m3/html-site
